# Generated by Django 2.2.12 on 2020-04-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200414_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoListManager',
        ),
    ]
