# Generated by Django 2.2.12 on 2020-04-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0009_auto_20200415_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
