# Generated by Django 2.2.12 on 2020-04-15 22:57

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0007_auto_20200415_2210'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('top_categories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(1, 'top'), (2, 'not_top')], default=1),
        ),
    ]
