# Generated by Django 2.2.12 on 2020-04-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
