# Generated by Django 2.2.12 on 2020-04-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0005_auto_20200415_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price',), 'verbose_name': 'Products'},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'name')},
        ),
    ]
