# Generated by Django 2.2.12 on 2020-04-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0008_auto_20200415_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
