# Generated by Django 2.2.12 on 2020-04-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0013_auto_20200416_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='home/dana/Рабочий стол/BFDjango/week12/todo/onlineShop/images'),
        ),
    ]
