# Generated by Django 2.2.12 on 2020-04-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0015_category_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='attachment',
            field=models.FileField(null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
